Feature/create skill system
Corvus-inc/EPAM_LearningGameProject pull request #24
Opened 2021-11-05 01:40 UTC by Corvus-inc

2021-11-05 16:25 UTC, Corvus-inc commented
Timer in skills mechanics  no react on pause. Need the issue for this the bug.

2021-11-07 12:32 UTC, pushkinman requested changes

2021-11-07 12:32 UTC, pushkinman commented on Assets/Scripts/Skills/SkillSystem.cs
> +        IsHeal.Invoke(_mSecForHealSkill);
```suggestion
        IsHeal?.Invoke(_mSecForHealSkill);
```

2021-11-07 12:32 UTC, pushkinman commented on Assets/Scripts/Skills/SkillSystem.cs
> +        IsBoostSpeed.Invoke(_mSecForBoostSkill);
```suggestion
        IsBoostSpeed?.Invoke(_mSecForBoostSkill);
```

2021-11-07 12:32 UTC, pushkinman commented on Assets/Scripts/Skills/SkillSystem.cs
> +        IsIncreaseDamage.Invoke(_mSecForDamageSkill);
```suggestion
        IsIncreaseDamage?.Invoke(_mSecForDamageSkill);
```

2021-11-07 12:32 UTC, pushkinman commented on Assets/Scripts/Skills/SkillSystem.cs
> +    }
Fix errors in other places to match this new constructor
```suggestion
    public SkillSystem(HealthSystem healthSystem, PlayerCharacter player, WeaponSystem weaponSystem)
    {
        _healthSystem = healthSystem;
        _player = player;
        _weaponSystem = weaponSystem;
        _currentWeapon = _weaponSystem.GetCurrentWeapon();
    }
```

2021-11-07 12:32 UTC, pushkinman commented on Assets/Scripts/Player/PlayerCharacter.cs
> +            PlayerWeapon = WeaponSystem.SwitchWeapon();
Pay close attention to your role separation, the player does not need to know that the bullets need to be returned to spawn, that is the responsibility of WeaponSystem, so it show look like this
```suggestion
            PlayerWeapon = WeaponSystem.SwitchWeapon();
```

2021-11-08 17:53 UTC, Corvus-inc commented on Assets/Scripts/Bullets/BaseBullet.cs
> +        OnActiveBullet();
these are the implementation features

2021-11-08 18:00 UTC, merged